_t[601]="end"
_t[602]=""
_t[603]="-- ─── ADD DELIVER PROMPT ───────────────────────────────────────────────────────"
_t[604]="addDeliverPrompt = function(npcId)"
_t[605]="    local data = npcs[npcId]"
_t[606]="    if not data then return end"
_t[607]="    local head = data.model:FindFirstChild(\"Head\")"
_t[608]="    if not head then return end"
_t[609]=""
_t[610]="    local existing = head:FindFirstChild(\"DeliverPrompt\")"
_t[611]="    if existing then existing:Destroy() end"
_t[612]=""
_t[613]="    local pp = Instance.new(\"ProximityPrompt\")"
_t[614]="    pp.Name                  = \"DeliverPrompt\""
_t[615]="    pp.ActionText            = \"Deliver Box\""
_t[616]="    pp.ObjectText            = data.name"
_t[617]="    pp.MaxActivationDistance = 8    -- M-8: tightened from 20 (must be physically close)"
_t[618]="    pp.HoldDuration          = 0"
_t[619]="    pp.RequiresLineOfSight   = false"
_t[620]="    pp.Parent                = head"
_t[621]=""
_t[622]="    pp.Triggered:Connect(function(player)"
_t[623]="        local d = npcs[npcId]"
_t[624]="        if not d or d.state ~= \"at_counter\" then return end"
_t[625]="        if d.deliveryLocked then return end"
_t[626]="        d.deliveryLocked = true"
_t[627]=""
_t[628]="        -- M-8: player must actually be carrying a box"
_t[629]="        if not OrderManager.IsCarryingBox(player) then"
_t[630]="            warn(\"[AntiExploit] \" .. player.Name .. \" triggered DeliverPrompt without a box\")"
_t[631]="            d.deliveryLocked = false"
_t[632]="            return"
_t[633]="        end"
_t[634]=""
_t[635]="        -- Search by npcId (works for both single-type and variety boxes)"
_t[636]="        local pendingKey, pending = nil, nil"
_t[637]="        for key, pb in pairs(pendingBoxes) do"
_t[638]="            if pb.npcId == npcId then pendingKey = key; pending = pb; break end"
_t[639]="        end"
_t[640]="        if not pending then"
_t[641]="            warn(\"[NPCController] No pending box for\", d.name)"
_t[642]="            d.deliveryLocked = false"
_t[643]="            return"
_t[644]="        end"
_t[645]=""
_t[646]="        if pending.carrier and pending.carrier ~= player.Name then"
_t[647]="            warn(\"[NPCController] Wrong carrier:\", player.Name, \"vs\", pending.carrier)"
_t[648]="            d.deliveryLocked = false"
_t[649]="            return"
_t[650]="        end"
_t[651]=""
_t[652]="        local ok, quality = OrderManager.DeliverBox(player, pending.boxId, d.order.orderId)"
_t[653]="        if not ok then"
_t[654]="            warn(\"[NPCController] DeliverBox failed for\", player.Name)"
_t[655]="            d.deliveryLocked = false"
_t[656]="            return"
_t[657]="        end"
_t[658]=""
_t[659]="        -- Transfer physical box model to NPC's arm"
_t[660]="        local transferEvent = ServerScriptService:FindFirstChild(\"BoxTransferToNPC\")"
_t[661]="        if transferEvent then transferEvent:Fire(player.Name, d.model) end"
_t[662]=""
_t[663]="        pendingBoxes[pendingKey] = nil"
_t[664]=""
_t[665]="        -- Stars from quality (0-100 weighted aggregate → 1-5 stars)"
_t[666]="        local stars = math.clamp(math.floor(1 + (quality / 100) * 4), 1, 5)"
_t[667]=""
_t[668]="        -- Combo: increment on ≥3 stars, reset below"
_t[669]="        local comboStreak"
_t[670]="        if stars >= 3 then"
_t[671]="            comboStreak = PlayerDataManager.IncrementCombo(player)"
_t[672]="        else"
_t[673]="            PlayerDataManager.ResetCombo(player)"
_t[674]="            comboStreak = 0"
_t[675]="        end"
_t[676]="        -- S-9: notify client of updated combo streak"
_t[677]="        comboUpdateRemote:FireClient(player, comboStreak)"
_t[678]=""
_t[679]="        -- Full payout via EconomyManager"
_t[680]="        -- timeRemaining=0, totalTime=1 → speedMult=1.0 (no timer tracking in M4)"
_t[681]="        local payout = EconomyManager.CalculatePayout("
_t[682]="            d.order.cookieId,"
_t[683]="            d.order.packSize,"
_t[684]="            stars,"
_t[685]="            0,            -- timeRemaining (not tracked in M4)"
_t[686]="            1,            -- totalTime"
_t[687]="            comboStreak,"
_t[688]="            d.isVIP"
_t[689]="        )"
_t[690]=""
_t[691]="        if rushHourActive then"
_t[692]="            payout.coins = math.floor(payout.coins * 1.5)"
_t[693]="        end"
_t[694]="        -- BUG-25: VIPPass gives delivering player 1.5x coin bonus"
_t[695]="        if GamepassManager.HasVIPPass(player) then"
_t[696]="            payout.coins = math.floor(payout.coins * 1.5)"
_t[697]="        end"
_t[698]="        -- Apply tip upgrade for the delivering player"
_t[699]="        do"
_t[700]="            local stations, _ = PlayerDataManager.GetUnlocks(player)"
_t[701]="            local hasTip2, hasTip1 = false, false"
_t[702]="            for _, id in ipairs(stations) do"
_t[703]="                if id == \"tip_boost_2\" then hasTip2 = true end"
_t[704]="                if id == \"tip_boost_1\" then hasTip1 = true end"
_t[705]="            end"
_t[706]="            local mult = hasTip2 and 1.20 or (hasTip1 and 1.10 or 1.0)"
_t[707]="            if mult > 1 then"
_t[708]="                payout.coins = math.floor(payout.coins * mult)"
_t[709]="            end"
_t[710]="        end"
_t[711]=""
_t[712]="        PlayerDataManager.RecordOrderComplete(player, stars == 5, d.order.packSize or 1)"
_t[713]="        PlayerDataManager.AddCoins(player, payout.coins)"
_t[714]="        PlayerDataManager.AddXP(player, payout.xp)"
_t[715]="        local profile = PlayerDataManager.GetData(player)"
_t[716]=""
_t[717]="        local coins = payout.coins"
_t[718]="        local xp    = payout.xp"
_t[719]=""
_t[720]="        deliveryResult:FireClient(player, stars, coins, xp, d.order.orderId)"
_t[721]="        boxCarriedRemote:FireClient(player, nil)  -- H-8: clear carry indicator"
_t[722]="        local _npcHead = d.model and d.model:FindFirstChild(\"Head\")"
_t[723]="        if _npcHead then deliveryFeedbackRemote:FireAllClients(_npcHead.Position, stars, player.Name) end"
_t[724]="        do"
_t[725]="            local _sse = game:GetService(\"ServerStorage\"):FindFirstChild(\"Events\")"
_t[726]="            local _be  = _sse and _sse:FindFirstChild(\"DeliveryPayout\")"
_t[727]="            if _be then _be:Fire({ playerName = player.Name, coins = coins }) end"
_t[728]="        end"
_t[729]="        SessionStats.RecordDelivery(stars, payout.coins, comboStreak, d.order.packSize or 1)"
_t[730]="        SessionStats.RecordStationScore(player, \"dress\", 1)  -- track deliveries for Employee of the Shift"
_t[731]="        DailyChallengeManager.RecordDelivery(player, {"
_t[732]="            stars       = stars,"
_t[733]="            cookieId    = d.order.cookieId,"
_t[734]="            coins       = payout.coins,"
_t[735]="            comboStreak = comboStreak,"
_t[736]="            packSize    = d.order.packSize or 1,"
_t[737]="        })"
_t[738]="        WeeklyChallengeManager.RecordDelivery(player, {"
_t[739]="            stars       = stars,"
_t[740]="            cookieId    = d.order.cookieId,"
_t[741]="            coins       = payout.coins,"
_t[742]="            comboStreak = comboStreak,"
_t[743]="            packSize    = d.order.packSize or 1,"
_t[744]="        })"
_t[745]="        LifetimeChallengeManager.CheckAll(player)"
_t[746]="        -- Advance tutorial step 9 gate (replaces TestNPCSpawner dependency)"
_t[747]="        do"
_t[748]="            local _evts = game:GetService(\"ServerStorage\"):FindFirstChild(\"Events\")"
_t[749]="            local _tde  = _evts and _evts:FindFirstChild(\"TutorialDelivered\")"
_t[750]="            if _tde then _tde:Fire(player) end"
_t[751]="        end"
_t[752]="        PlayerDataManager.AwardBakeryXP(player, 15 + stars * 5)"
_t[753]="        hudUpdate:FireClient(player,"
_t[754]="            profile and profile.coins or 0,"
_t[755]="            profile and profile.xp    or 0,"
_t[756]="            nil)"
_t[757]=""
_t[758]="        updateTabletDisplay(nil)"
_t[759]=""
_t[760]="        print(string.format(\"[NPCController] %s delivered to %s | q=%d%% coins=%d stars=%d\","
_t[761]="            player.Name, d.name, quality, coins, stars))"
_t[762]=""
_t[763]="        d.deliveryLocked = false"
_t[764]="        npcLeave(npcId, \"delivered\")"
_t[765]="    end)"
_t[766]="end"
_t[767]=""
_t[768]="-- ─── PATIENCE TICKER ──────────────────────────────────────────────────────────"
_t[769]="local function startPatienceTicker(npcId)"
_t[770]="    task.spawn(function()"
_t[771]="        while true do"
_t[772]="            task.wait(1)"
_t[773]="            local data = npcs[npcId]"
_t[774]="            if not data then break end"
_t[775]=""
_t[776]="            if data.state == \"seated\" or data.state == \"at_counter\" then"
_t[777]="                -- Patience only ticks after order is taken (seated/at_counter), not while waiting in queue"
_t[778]="                data.patience -= 1"
_t[779]="                NPCSpawner.SetTimerText(data.model, formatTime(data.patience))"
_t[780]="                -- M-1: update in-world patience bar every tick"
_t[781]="                local maxP = data.maxPatience or data.patience"
_t[782]="                if maxP > 0 then"
_t[783]="                    NPCSpawner.SetPatienceBar(data.model, data.patience / maxP)"
_t[784]="                end"
_t[785]="                -- S-6: broadcast patience ratio to all clients every 5 ticks"
_t[786]="                if data.patience % 5 == 0 and data.order then"
_t[787]="                    npcPatienceRemote:FireAllClients("
_t[788]="                        data.order.orderId,"
_t[789]="                        data.patience,"
_t[790]="                        data.maxPatience or data.patience,"
_t[791]="                        data.model"
_t[792]="                    )"
_t[793]="                end"
_t[794]="                -- Impatient head-bob at <=30% patience"
_t[795]="                local maxP = data.maxPatience or data.patience"
_t[796]="                if maxP > 0 and data.patience == math.floor(maxP * 0.30) then"
_t[797]="                    local head = data.model and data.model:FindFirstChild(\"Head\")"
_t[798]="                    if head then"
_t[799]="                        task.spawn(function()"
_t[800]="                            local TW = game:GetService(\"TweenService\")"
_t[801]="                            local TI = TweenInfo.new(0.18, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut, 3, true)"
_t[802]="                            local orig = head.CFrame"
_t[803]="                            TW:Create(head, TI, { CFrame = orig * CFrame.Angles(0, 0, math.rad(12)) }):Play()"
_t[804]="                        end)"
_t[805]="                    end"
_t[806]="                end"
_t[807]="                if data.patience <= 0 then"
_t[808]="                    npcLeave(npcId, \"patience_expired\")"
_t[809]="                    break"
_t[810]="                end"
_t[811]="            else"
_t[812]="                NPCSpawner.SetTimerText(data.model, \"\")"
_t[813]="            end"
_t[814]="        end"
_t[815]="    end)"
_t[816]="end"
_t[817]=""
_t[818]="-- ─── SPAWN NPC ────────────────────────────────────────────────────────────────"
_t[819]="local function spawnNPC()"
_t[820]="    if countNPCs() >= MAX_NPCS_IN_SCENE then return end"
_t[821]="    if #npcQueue >= MAX_QUEUE_SIZE then return end"
_t[822]=""
_t[823]="    local slot  = #npcQueue + 1"
_t[824]="    local npcId = nextNpcId"
_t[825]="    nextNpcId  += 1"
_t[826]=""
_t[827]="    local name  = pickRandomName()"
_t[828]="    local isVIP = math.random() < VIP_CHANCE"
_t[829]=""
_t[830]="    local model = NPCSpawner.CreateNPC({"
_t[831]="        name        = name,"
_t[832]="        isVIP       = isVIP,"
_t[833]="        spawnCFrame = getSpawnCFrame(),"
_t[834]="    })"
_t[835]="    if not model then return end"
_t[836]=""
_t[837]="    -- BUG-13: Put NPC HRP in \"NPCs\" group — prevents HRP-HRP collisions between NPCs"
_t[838]="    local npcHrp = model:FindFirstChild(\"HumanoidRootPart\")"
_t[839]="    if npcHrp then"
_t[840]="        pcall(function()"
_t[841]="            PhysicsService:SetPartCollisionGroup(npcHrp, \"NPCs\")"
_t[842]="        end)"
_t[843]="    end"
_t[844]=""
_t[845]="    local data = {"
_t[846]="        id              = npcId,"
_t[847]="        name            = name,"
_t[848]="        model           = model,"
_t[849]="        isVIP           = isVIP,"
_t[850]="        state           = \"queuing\","
_t[851]="        patience        = getPatienceTime(),"
_t[852]="        maxPatience     = getPatienceTime(),  -- S-6: store initial value for ratio calc"
_t[853]="        queueSlot       = slot,"
_t[854]="        waitSpot        = nil,"
_t[855]="        order           = nil,"
_t[856]="        cancelMove      = nil,"
_t[857]="        promptConnected = false,"
_t[858]="        assignedBoxId   = nil,"
_t[859]="    }"
_t[860]="    npcs[npcId] = data"
_t[861]="    table.insert(npcQueue, npcId)"
_t[862]=""
_t[863]="    local queuePos = getQueuePos(slot)"
_t[864]="    if queuePos then"
_t[865]="        data.cancelMove = NPCSpawner.MoveTo(model, queuePos, function()"
_t[866]="            local d = npcs[npcId]"
_t[867]="            if not d then return end"
_t[868]="            d.state      = \"waiting_in_queue\""
_t[869]="            d.cancelMove = nil"
_t[870]=""
_t[871]="            -- Face counter while waiting to order"
_t[872]="            facePosition(model, getCounterPos())"
_t[873]=""
_t[874]="            -- Connect order prompt once"
_t[875]="            if not d.promptConnected then"
_t[876]="                d.promptConnected = true"
_t[877]="                local pp = NPCSpawner.GetPrompt(model)"
_t[878]="                if pp then"
_t[879]="                    pp.Triggered:Connect(function(player)"
_t[880]="                        local current = npcs[npcId]"
_t[881]="                        if current"
_t[882]="                            and current.queueSlot == 1"
_t[883]="                            and current.state == \"waiting_in_queue\""
_t[884]="                        then"
_t[885]="                            takeOrder(player, npcId)"
_t[886]="                        end"
_t[887]="                    end)"
_t[888]="                end"
_t[889]="            end"
_t[890]=""
_t[891]="            if d.queueSlot == 1 then"
_t[892]="                NPCSpawner.SetPromptEnabled(model, true)"
_t[893]="            end"
_t[894]="        end)"
_t[895]="    else"
_t[896]="        data.state = \"waiting_in_queue\""
_t[897]="        if slot == 1 then NPCSpawner.SetPromptEnabled(model, true) end"
_t[898]="    end"
_t[899]=""
_t[900]="    -- Safety: if still queuing after 15s (stuck on rope/barrier en route to queue spot),"