_t[301]="            -- Shuffle available types"
_t[302]="            for i = #availableTypes, 2, -1 do"
_t[303]="                local j = math.random(i)"
_t[304]="                availableTypes[i], availableTypes[j] = availableTypes[j], availableTypes[i]"
_t[305]="            end"
_t[306]="            local chosenTypes = {}"
_t[307]="            for i = 1, numTypes do chosenTypes[i] = availableTypes[i] end"
_t[308]=""
_t[309]="            -- Distribute slots (each type gets ≥1, extras random)"
_t[310]="            local slotCounts = {}"
_t[311]="            for _, t in ipairs(chosenTypes) do slotCounts[t] = 1 end"
_t[312]="            local rem = packSize - numTypes"
_t[313]="            while rem > 0 do"
_t[314]="                local t = chosenTypes[math.random(1, #chosenTypes)]"
_t[315]="                slotCounts[t] += 1"
_t[316]="                rem -= 1"
_t[317]="            end"
_t[318]=""
_t[319]="            -- m8: validate warmer has enough stock to cover each type's slot count"
_t[320]="            local stockOk = true"
_t[321]="            for t, need in pairs(slotCounts) do"
_t[322]="                if (warmerCounts[t] or 0) < need then stockOk = false; break end"
_t[323]="            end"
_t[324]="            if not stockOk then"
_t[325]="                -- Not enough stock for this variety distribution — fall back to single-type"
_t[326]="                cookie   = CookieData.GetRandomFromMenu(MenuManager.GetActiveMenu())"
_t[327]="                packSize = PACK_SIZES[math.random(1, #PACK_SIZES)]"
_t[328]="                price    = calcPrice(cookie.id, packSize)"
_t[329]="            else"
_t[330]=""
_t[331]="            -- Build & shuffle items array"
_t[332]="            varItems = {}"
_t[333]="            for _, t in ipairs(chosenTypes) do"
_t[334]="                for _ = 1, slotCounts[t] do table.insert(varItems, t) end"
_t[335]="            end"
_t[336]="            for i = #varItems, 2, -1 do"
_t[337]="                local j = math.random(i)"
_t[338]="                varItems[i], varItems[j] = varItems[j], varItems[i]"
_t[339]="            end"
_t[340]=""
_t[341]="            -- Primary cookie = most expensive (for payout calc)"
_t[342]="            local maxP = 0"
_t[343]="            cookie = CookieData.GetById(chosenTypes[1])"
_t[344]="            for _, t in ipairs(chosenTypes) do"
_t[345]="                local c = CookieData.GetById(t)"
_t[346]="                if c and (c.price or 0) > maxP then maxP = c.price; cookie = c end"
_t[347]="            end"
_t[348]=""
_t[349]="            -- Price = sum of each type's price × slot count"
_t[350]="            price = 0"
_t[351]="            for t, cnt in pairs(slotCounts) do"
_t[352]="                local c = CookieData.GetById(t)"
_t[353]="                price += (c and c.price or 5) * cnt"
_t[354]="            end"
_t[355]="            end -- close stockOk else"
_t[356]="        else"
_t[357]="            -- ── Single-type order ─────────────────────────────────────────────"
_t[358]="            cookie   = CookieData.GetRandomFromMenu(MenuManager.GetActiveMenu())"
_t[359]="            packSize = PACK_SIZES[math.random(1, #PACK_SIZES)]"
_t[360]="            price    = calcPrice(cookie.id, packSize)"
_t[361]="        end"
_t[362]="    end"
_t[363]=""
_t[364]="    -- Store order data — confirmed in Step 2 (confirmOrder)"
_t[365]="    data.order = {"
_t[366]="        cookieId   = cookie.id,"
_t[367]="        cookieName = varItems and \"Variety Pack\" or cookie.name,"
_t[368]="        packSize   = packSize,"
_t[369]="        price      = price,"
_t[370]="        isVIP      = data.isVIP,"
_t[371]="        orderId    = nil,"
_t[372]="        items      = varItems,"
_t[373]="        isVariety  = varItems ~= nil,"
_t[374]="    }"
_t[375]="    data.state            = \"cutscene_pending\""
_t[376]="    data.triggeringPlayer = player  -- track who triggered so PlayerRemoving confirms the right player"
_t[377]="    data.cancelMove       = nil     -- NPC is stationary at slot 1; clear any stale handle"
_t[378]="    NPCSpawner.SetPromptEnabled(data.model, false)"
_t[379]=""
_t[380]="    -- Advance queue now so next NPC can move up"
_t[381]="    for i, id in ipairs(npcQueue) do"
_t[382]="        if id == npcId then"
_t[383]="            table.remove(npcQueue, i)"
_t[384]="            break"
_t[385]="        end"
_t[386]="    end"
_t[387]="    advanceQueue()"
_t[388]=""
_t[389]="    -- Fire cutscene to this player"
_t[390]="    startOrderCutsceneRemote:FireClient(player, {"
_t[391]="        npcId      = npcId,"
_t[392]="        npcName    = data.name,"
_t[393]="        cookieId   = cookie.id,"
_t[394]="        cookieName = data.order.cookieName,"
_t[395]="        packSize   = packSize,"
_t[396]="        baseCoins  = price,"
_t[397]="        isVIP      = data.isVIP,"
_t[398]="        items      = varItems,"
_t[399]="    })"
_t[400]=""
_t[401]="    local logLabel = varItems and (\"VARIETY ×\" .. packSize) or (cookie.id .. \" x\" .. packSize)"
_t[402]="    print(string.format(\"[NPCController] Cutscene fired to %s for NPC %s (%s)\","
_t[403]="        player.Name, data.name, logLabel))"
_t[404]="end"
_t[405]=""
_t[406]="-- ─── CONFIRM ORDER (called when client dismisses cutscene) ────────────────────"
_t[407]="local function confirmOrder(player, npcId)"
_t[408]="    local data = npcs[npcId]"
_t[409]="    if not data then"
_t[410]="        warn(\"[NPCController] confirmOrder: npcId not found:\", npcId)"
_t[411]="        return"
_t[412]="    end"
_t[413]="    if data.state ~= \"cutscene_pending\" then"
_t[414]="        warn(\"[NPCController] confirmOrder: unexpected state:\", data.state)"
_t[415]="        return"
_t[416]="    end"
_t[417]="    if data.triggeringPlayer and data.triggeringPlayer ~= player then"
_t[418]="        warn(\"[AntiExploit] \" .. player.Name .. \" tried to confirm another player's cutscene npcId=\" .. tostring(npcId))"
_t[419]="        return"
_t[420]="    end"
_t[421]="    data.triggeringPlayer = nil  -- clear now that cutscene is resolved"
_t[422]=""
_t[423]="    -- Register with OrderManager"
_t[424]="    local order = OrderManager.AddNPCOrder(data.name, data.order.cookieId, {"
_t[425]="        packSize = data.order.packSize,"
_t[426]="        price    = data.order.price,"
_t[427]="        isVIP    = data.order.isVIP,"
_t[428]="        npcId    = npcId,"
_t[429]="        items    = data.order.items,"
_t[430]="    })"
_t[431]="    data.order.orderId = order.orderId"
_t[432]="    data.state = \"ordered\""
_t[433]="    npcOrderReadyRemote:FireAllClients(order.orderId, data.order.cookieId)"
_t[434]=""
_t[435]="    -- Update 3D tablet display"
_t[436]="    updateTabletDisplay({"
_t[437]="        cookieId = data.order.cookieId,"
_t[438]="        packSize = data.order.packSize,"
_t[439]="        price    = data.order.price,"
_t[440]="        isVIP    = data.order.isVIP,"
_t[441]="        status   = \"In kitchen...\","
_t[442]="    })"
_t[443]=""
_t[444]="    -- Update player's HUD active order label"
_t[445]="    pcall(function()"
_t[446]="        local label = data.order.isVariety"
_t[447]="            and buildVarietyLabel(data.order.items)"
_t[448]="            or  (data.order.cookieName .. \" x\" .. data.order.packSize)"
_t[449]="        hudUpdate:FireClient(player, nil, nil, label, order.orderId)"
_t[450]="    end)"
_t[451]=""
_t[452]="    -- Walk to a waiting area spot"
_t[453]="    local spot = getFreeWaitSpot()"
_t[454]="    if spot then"
_t[455]="        data.waitSpot   = spot.Name"
_t[456]="        data.state      = \"walking_to_seat\""
_t[457]="        data.cancelMove = NPCSpawner.MoveTo(data.model, spot.Position + Vector3.new(0, 2, 0), function()"
_t[458]="            local d = npcs[npcId]"
_t[459]="            if not d then return end"
_t[460]="            d.state = \"seated\""
_t[461]="            if d.pendingCallToCounter then"
_t[462]="                d.pendingCallToCounter = nil"
_t[463]="                callNPCToCounter(npcId)"
_t[464]="            end"
_t[465]="        end)"
_t[466]="        -- Safety timeout: if still walking_to_seat after 12s (pathfinding stuck),"
_t[467]="        -- force to seated so pendingCallToCounter can fire."
_t[468]="        task.delay(12, function()"
_t[469]="            local d = npcs[npcId]"
_t[470]="            if d and d.state == \"walking_to_seat\" then"
_t[471]="                warn(\"[NPCController] \" .. d.name .. \" stuck walking to seat — forcing seated\")"
_t[472]="                d.state = \"seated\""
_t[473]="                if d.cancelMove then pcall(d.cancelMove); d.cancelMove = nil end"
_t[474]="                if d.pendingCallToCounter then"
_t[475]="                    d.pendingCallToCounter = nil"
_t[476]="                    callNPCToCounter(npcId)"
_t[477]="                end"
_t[478]="            end"
_t[479]="        end)"
_t[480]="    else"
_t[481]="        data.state = \"seated\""
_t[482]="    end"
_t[483]=""
_t[484]="    print(string.format(\"[NPCController] Order confirmed: %s %dx %s | price=%d | orderId=%s\","
_t[485]="        data.name, data.order.packSize,"
_t[486]="        data.order.isVariety and \"VARIETY\" or data.order.cookieId,"
_t[487]="        data.order.price, tostring(data.order.orderId)))"
_t[488]="end"
_t[489]=""
_t[490]="confirmOrderRemote.OnServerEvent:Connect(function(player, npcId)"
_t[491]="    if type(npcId) ~= \"number\" then return end"
_t[492]="    confirmOrder(player, npcId)"
_t[493]="end)"
_t[494]=""
_t[495]="-- ─── NPC LEAVE ────────────────────────────────────────────────────────────────"
_t[496]="npcLeave = function(npcId, reason)"
_t[497]="    local data = npcs[npcId]"
_t[498]="    if not data then return end"
_t[499]="    if data.state == \"leaving\" then return end"
_t[500]=""
_t[501]="    data.state = \"leaving\""
_t[502]="    NPCSpawner.SetPromptEnabled(data.model, false)"
_t[503]=""
_t[504]="    if data.cancelMove then"
_t[505]="        pcall(data.cancelMove)"
_t[506]="        data.cancelMove = nil"
_t[507]="    end"
_t[508]=""
_t[509]="    for i, id in ipairs(npcQueue) do"
_t[510]="        if id == npcId then"
_t[511]="            table.remove(npcQueue, i)"
_t[512]="            break"
_t[513]="        end"
_t[514]="    end"
_t[515]=""
_t[516]="    -- Cancel any box made for this NPC and return cookies to warmer"
_t[517]="    -- Search by npcId so variety boxes (keyed as \"variety\") are also found"
_t[518]="    local pendingKey, pending = nil, nil"
_t[519]="    for key, pb in pairs(pendingBoxes) do"
_t[520]="        if pb.npcId == npcId then pendingKey = key; pending = pb; break end"
_t[521]="    end"
_t[522]="    if pending then"
_t[523]="        OrderManager.CancelBox(pending.boxId)"
_t[524]="        if pending.carrier then"
_t[525]="            local carrier = Players:FindFirstChild(pending.carrier)"
_t[526]="            if carrier then"
_t[527]="                forceDropBoxRemote:FireClient(carrier)"
_t[528]="                -- Destroy physical carry model and restore player arms"
_t[529]="                local boxModel = workspace:FindFirstChild(\"CarriedBox_\" .. pending.carrier)"
_t[530]="                if boxModel then boxModel:Destroy() end"
_t[531]="                local char = carrier.Character"
_t[532]="                local torso = char and char:FindFirstChild(\"Torso\")"
_t[533]="                if torso then"
_t[534]="                    local rs = torso:FindFirstChild(\"Right Shoulder\")"
_t[535]="                    local ls = torso:FindFirstChild(\"Left Shoulder\")"
_t[536]="                    if rs then rs.C0 = CFrame.new(1,  0.5, 0) * CFrame.Angles(0,  math.pi/2, 0) end"
_t[537]="                    if ls then ls.C0 = CFrame.new(-1, 0.5, 0) * CFrame.Angles(0, -math.pi/2, 0) end"
_t[538]="                end"
_t[539]="            end"
_t[540]="        end"
_t[541]="        pendingBoxes[pendingKey] = nil"
_t[542]="    end"
_t[543]=""
_t[544]="    -- Remove this NPC's order from the KDS queue and notify all clients"
_t[545]="    if data.order and data.order.orderId then"
_t[546]="        OrderManager.CancelNPCOrder(data.order.orderId)"
_t[547]="        -- Tell HUDController to remove this order from the active-order pill"
_t[548]="        npcOrderCancelledRemote:FireAllClients(data.order.orderId, data.order.cookieId, data.order.packSize)"
_t[549]="        -- S-4: if NPC left due to patience expiry, broadcast fail state + apply coin penalty"
_t[550]="        if reason == \"patience_expired\" or reason == \"counter_timeout\" then"
_t[551]="            do"
_t[552]="                local _fHead = data.model and data.model:FindFirstChild(\"Head\")"
_t[553]="                npcOrderFailedRemote:FireAllClients(data.name, data.order.orderId, _fHead and _fHead.Position or nil)"
_t[554]="            end"
_t[555]="            SessionStats.RecordFail()"
_t[556]="            -- Deduct penalty from all active players"
_t[557]="            local FAIL_PENALTY = 75"
_t[558]="            for _, p in ipairs(Players:GetPlayers()) do"
_t[559]="                PlayerDataManager.AddCoins(p, -FAIL_PENALTY)"
_t[560]="            end"
_t[561]="        end"
_t[562]="    end"
_t[563]=""
_t[564]="    npcs[npcId] = nil"
_t[565]=""
_t[566]="    local exitModel = data.model"
_t[567]="    local exitPos   = SPAWN_PART and (SPAWN_PART.Position + Vector3.new(0, 2, 0)) or Vector3.new(0, 2, 28)"
_t[568]="    NPCSpawner.MoveTo(exitModel, exitPos, function() NPCSpawner.Remove(exitModel) end)"
_t[569]="    task.delay(15, function() if exitModel and exitModel.Parent then exitModel:Destroy() end end)"
_t[570]=""
_t[571]="    advanceQueue()"
_t[572]="    print(string.format(\"[NPCController] %s left (%s)\", data.name, reason or \"unknown\"))"
_t[573]="end"
_t[574]=""
_t[575]="-- ─── ADVANCE QUEUE ────────────────────────────────────────────────────────────"
_t[576]="advanceQueue = function()"
_t[577]="    for pos, npcId in ipairs(npcQueue) do"
_t[578]="        local data = npcs[npcId]"
_t[579]="        if data then"
_t[580]="            local wasFirst = (data.queueSlot == 1)"
_t[581]="            data.queueSlot = pos"
_t[582]=""
_t[583]="            if data.state == \"waiting_in_queue\" then"
_t[584]="                if pos == 1 and not wasFirst then"
_t[585]="                    NPCSpawner.SetPromptEnabled(data.model, true)"
_t[586]="                elseif pos ~= 1 then"
_t[587]="                    NPCSpawner.SetPromptEnabled(data.model, false)"
_t[588]="                end"
_t[589]="                local newPos = getQueuePos(pos)"
_t[590]="                if newPos then"
_t[591]="                    if data.cancelMove then pcall(data.cancelMove) end"
_t[592]="                    local advModel = data.model"
_t[593]="                    data.cancelMove = NPCSpawner.MoveTo(data.model, newPos, function()"
_t[594]="                        -- BUG-2: re-face counter after advancing to new queue slot"
_t[595]="                        facePosition(advModel, getCounterPos())"
_t[596]="                    end)"
_t[597]="                end"
_t[598]="            end"
_t[599]="        end"
_t[600]="    end"