_t[901]="    -- teleport directly to the queue position and transition to waiting_in_queue."
_t[902]="    task.delay(15, function()"
_t[903]="        local d = npcs[npcId]"
_t[904]="        if not d or d.state ~= \"queuing\" then return end"
_t[905]="        warn(\"[NPCController] \" .. d.name .. \" stuck queuing — teleporting to queue spot\")"
_t[906]="        if d.cancelMove then pcall(d.cancelMove); d.cancelMove = nil end"
_t[907]="        local qp = getQueuePos(d.queueSlot)"
_t[908]="        if qp and d.model and d.model.PrimaryPart then"
_t[909]="            d.model:SetPrimaryPartCFrame(CFrame.new(qp))"
_t[910]="        end"
_t[911]="        d.state = \"waiting_in_queue\""
_t[912]="        facePosition(d.model, getCounterPos())"
_t[913]="        if not d.promptConnected then"
_t[914]="            d.promptConnected = true"
_t[915]="            local pp = NPCSpawner.GetPrompt(d.model)"
_t[916]="            if pp then"
_t[917]="                pp.Triggered:Connect(function(player)"
_t[918]="                    local current = npcs[npcId]"
_t[919]="                    if current and current.queueSlot == 1 and current.state == \"waiting_in_queue\" then"
_t[920]="                        takeOrder(player, npcId)"
_t[921]="                    end"
_t[922]="                end)"
_t[923]="            end"
_t[924]="        end"
_t[925]="        if d.queueSlot == 1 then"
_t[926]="            NPCSpawner.SetPromptEnabled(d.model, true)"
_t[927]="        end"
_t[928]="    end)"
_t[929]=""
_t[930]="    startPatienceTicker(npcId)"
_t[931]="    print(string.format(\"[NPCController] Spawned %s (id=%d, VIP=%s, slot=%d)\", name, npcId, tostring(isVIP), slot))"
_t[932]="end"
_t[933]=""
_t[934]="-- ─── BOX READY → CALL NPC TO COUNTER ─────────────────────────────────────────"
_t[935]="local COUNTER_TIMEOUT = 90  -- seconds before NPC gives up at counter"
_t[936]=""
_t[937]="local function callNPCToCounter(npcId)"
_t[938]="    local data = npcs[npcId]"
_t[939]="    if not data then return end"
_t[940]="    data.state      = \"walking_to_counter\""
_t[941]="    data.cancelMove = NPCSpawner.MoveTo(data.model, getCounterPos(), function()"
_t[942]="        local d = npcs[npcId]"
_t[943]="        if not d then return end"
_t[944]="        d.state      = \"at_counter\""
_t[945]="        d.cancelMove = nil"
_t[946]="        addDeliverPrompt(npcId)"
_t[947]="        print(string.format(\"[NPCController] %s at counter, ready for delivery\", d.name))"
_t[948]="        task.delay(COUNTER_TIMEOUT, function()"
_t[949]="            local still = npcs[npcId]"
_t[950]="            if still and still.state == \"at_counter\" then"
_t[951]="                npcLeave(npcId, \"counter_timeout\")"
_t[952]="            end"
_t[953]="        end)"
_t[954]="    end)"
_t[955]="end"
_t[956]=""
_t[957]="OrderManager.On(\"BoxCreated\", function(box)"
_t[958]="    if not box.cookieId then return end"
_t[959]=""
_t[960]="    -- Find an NPC waiting for this box (seated, walking to seat, or just ordered)"
_t[961]="    for npcId, data in pairs(npcs) do"
_t[962]="        local cookieMatch  = not box.isVariety and data.order and data.order.cookieId == box.cookieId"
_t[963]="        local varietyMatch = box.isVariety and data.order and data.order.isVariety == true"
_t[964]="        local stateOk      = data.state == \"seated\" or data.state == \"walking_to_seat\" or data.state == \"ordered\""
_t[965]="        if stateOk and (cookieMatch or varietyMatch) then"
_t[966]="            data.assignedBoxId = box.boxId"
_t[967]="            -- If box was made by an AI worker (not a real player), any player can deliver"
_t[968]="            local isRealPlayer = Players:FindFirstChild(box.carrier) ~= nil"
_t[969]="            pendingBoxes[pendingKeyForNpc(npcId)] = {"
_t[970]="                boxId   = box.boxId,"
_t[971]="                carrier = isRealPlayer and box.carrier or nil,"
_t[972]="                npcId   = npcId,"
_t[973]="            }"
_t[974]="            -- H-8: notify the carrier so the HUD carry pill shows the NPC name"
_t[975]="            if isRealPlayer then"
_t[976]="                local carrierPlayer = Players:FindFirstChild(box.carrier)"
_t[977]="                if carrierPlayer then"
_t[978]="                    boxCarriedRemote:FireClient(carrierPlayer, data.name)"
_t[979]="                end"
_t[980]="            end"
_t[981]=""
_t[982]="            if data.state == \"seated\" then"
_t[983]="                callNPCToCounter(npcId)"
_t[984]="            else"
_t[985]="                -- NPC is still walking to their seat; flag them to head to counter once seated"
_t[986]="                data.pendingCallToCounter = true"
_t[987]="            end"
_t[988]=""
_t[989]="            print(string.format(\"[NPCController] Calling %s to counter (box #%d, %s)\","
_t[990]="                data.name, box.boxId, box.cookieId))"
_t[991]="            break"
_t[992]="        end"
_t[993]="    end"
_t[994]="end)"
_t[995]=""
_t[996]="-- ─── TUTORIAL NPC (BUG-46) ───────────────────────────────────────────────────"
_t[997]="-- Spawns a pre-ordered tutorial NPC with chocolate_chip × 6 directly in"
_t[998]="-- \"ordered\" state, bypassing the queue/GameState check."
_t[999]="-- Fired by TutorialController after the player completes the oven step (step 3→4)."
_t[1000]="local function spawnTutorialNPC()"
_t[1001]="    local npcId    = nextNpcId"
_t[1002]="    nextNpcId     += 1"
_t[1003]="    local name     = \"Tutorial Customer\""
_t[1004]="    local cookieId = \"chocolate_chip\""
_t[1005]="    local packSize = 6"
_t[1006]="    local cookie   = CookieData.GetById(cookieId)"
_t[1007]="    local price    = (cookie and cookie.price or 5) * packSize"
_t[1008]=""
_t[1009]="    local model = NPCSpawner.CreateNPC({"
_t[1010]="        name        = name,"
_t[1011]="        isVIP       = false,"
_t[1012]="        spawnCFrame = getSpawnCFrame(),"
_t[1013]="    })"
_t[1014]="    if not model then"
_t[1015]="        warn(\"[NPCController] spawnTutorialNPC: failed to create NPC model\")"
_t[1016]="        return"
_t[1017]="    end"
_t[1018]=""
_t[1019]="    -- BUG-13: keep tutorial NPC out of the NPC-NPC collision group"
_t[1020]="    local npcHrp = model:FindFirstChild(\"HumanoidRootPart\")"
_t[1021]="    if npcHrp then"
_t[1022]="        pcall(function() PhysicsService:SetPartCollisionGroup(npcHrp, \"NPCs\") end)"
_t[1023]="    end"
_t[1024]=""
_t[1025]="    -- Register order in OrderManager so the Dress KDS shows it"
_t[1026]="    local order = OrderManager.AddNPCOrder(name, cookieId, {"
_t[1027]="        packSize = packSize,"
_t[1028]="        price    = price,"
_t[1029]="        isVIP    = false,"
_t[1030]="        npcId    = npcId,"
_t[1031]="        items    = nil,"
_t[1032]="    })"
_t[1033]=""
_t[1034]="    local maxP = getPatienceTime() * 3  -- generous patience for tutorial"
_t[1035]="    local data = {"
_t[1036]="        id              = npcId,"
_t[1037]="        name            = name,"
_t[1038]="        model           = model,"
_t[1039]="        isVIP           = false,"
_t[1040]="        state           = \"ordered\",  -- skip queue; order already placed"
_t[1041]="        patience        = maxP,"
_t[1042]="        maxPatience     = maxP,"
_t[1043]="        queueSlot       = nil,"
_t[1044]="        waitSpot        = nil,"
_t[1045]="        order           = {"
_t[1046]="            cookieId   = cookieId,"
_t[1047]="            cookieName = cookie and cookie.name or cookieId,"
_t[1048]="            packSize   = packSize,"
_t[1049]="            price      = price,"
_t[1050]="            isVIP      = false,"
_t[1051]="            orderId    = order.orderId,"
_t[1052]="            isVariety  = false,"
_t[1053]="            items      = nil,"
_t[1054]="        },"
_t[1055]="        cancelMove      = nil,"
_t[1056]="        promptConnected = false,"
_t[1057]="        assignedBoxId   = nil,"
_t[1058]="    }"
_t[1059]="    npcs[npcId] = data"
_t[1060]=""
_t[1061]="    npcOrderReadyRemote:FireAllClients(order.orderId, cookieId)"
_t[1062]=""
_t[1063]="    -- Walk NPC to a free waiting area spot"
_t[1064]="    local spot = getFreeWaitSpot()"
_t[1065]="    if spot then"
_t[1066]="        data.waitSpot   = spot.Name"
_t[1067]="        data.state      = \"walking_to_seat\""
_t[1068]="        data.cancelMove = NPCSpawner.MoveTo(data.model, spot.Position + Vector3.new(0, 2, 0), function()"
_t[1069]="            local d = npcs[npcId]"
_t[1070]="            if not d then return end"
_t[1071]="            d.state = \"seated\""
_t[1072]="            if d.pendingCallToCounter then"
_t[1073]="                d.pendingCallToCounter = nil"
_t[1074]="                callNPCToCounter(npcId)"
_t[1075]="            end"
_t[1076]="        end)"
_t[1077]="        task.delay(12, function()"
_t[1078]="            local d = npcs[npcId]"
_t[1079]="            if d and d.state == \"walking_to_seat\" then"
_t[1080]="                d.state = \"seated\""
_t[1081]="                if d.cancelMove then pcall(d.cancelMove); d.cancelMove = nil end"
_t[1082]="                if d.pendingCallToCounter then"
_t[1083]="                    d.pendingCallToCounter = nil"
_t[1084]="                    callNPCToCounter(npcId)"
_t[1085]="                end"
_t[1086]="            end"
_t[1087]="        end)"
_t[1088]="    else"
_t[1089]="        data.state = \"seated\""
_t[1090]="    end"
_t[1091]=""
_t[1092]="    startPatienceTicker(npcId)"
_t[1093]="    print(string.format(\"[NPCController] Tutorial NPC spawned: %s (id=%d, %s x%d, orderId=%s)\","
_t[1094]="        name, npcId, cookieId, packSize, tostring(order.orderId)))"
_t[1095]="end"
_t[1096]=""
_t[1097]="-- Listen for SpawnTutorialNPC BindableEvent (created by TutorialController's fix)"
_t[1098]="task.spawn(function()"
_t[1099]="    local evts = game:GetService(\"ServerStorage\"):WaitForChild(\"Events\", 10)"
_t[1100]="    if not evts then warn(\"[NPCController] ServerStorage/Events not found for SpawnTutorialNPC\"); return end"
_t[1101]="    local e = evts:WaitForChild(\"SpawnTutorialNPC\", 15)"
_t[1102]="    if not e then warn(\"[NPCController] SpawnTutorialNPC BindableEvent not found\"); return end"
_t[1103]="    e.Event:Connect(function()"
_t[1104]="        spawnTutorialNPC()"
_t[1105]="    end)"
_t[1106]="    print(\"[NPCController] SpawnTutorialNPC gate wired\")"
_t[1107]="end)"
_t[1108]=""
_t[1109]="-- ─── SPAWN LOOP ───────────────────────────────────────────────────────────────"
_t[1110]="task.spawn(function()"
_t[1111]="    task.wait(2)  -- brief startup buffer before first spawn attempt"
_t[1112]="    while true do"
_t[1113]="        if isSpawnAllowed() then spawnNPC() end"
_t[1114]="        task.wait(rushHourActive and RUSH_SPAWN_INTERVAL or SPAWN_INTERVAL)"
_t[1115]="    end"
_t[1116]="end)"
_t[1117]=""
_t[1118]="-- Stagger a second NPC 25s after game opens"
_t[1119]="task.delay(25, function()"
_t[1120]="    if isSpawnAllowed() then spawnNPC() end"
_t[1121]="end)"
_t[1122]=""
_t[1123]="-- Empty-lobby fast-spawn: if Open and no NPCs present, spawn after 10s gap"
_t[1124]="task.spawn(function()"
_t[1125]="    while true do"
_t[1126]="        task.wait(10)"
_t[1127]="        if isSpawnAllowed() and countNPCs() == 0 then"
_t[1128]="            spawnNPC()"
_t[1129]="        end"
_t[1130]="    end"
_t[1131]="end)"
_t[1132]=""
_t[1133]="-- Spawn NPCs immediately when Open phase begins (no 60s wait)"
_t[1134]="workspace:GetAttributeChangedSignal(\"GameState\"):Connect(function()"
_t[1135]="    local state = workspace:GetAttribute(\"GameState\")"
_t[1136]="    if state == \"Open\" then"
_t[1137]="        task.wait(2)"
_t[1138]="        spawnNPC()"
_t[1139]="        task.delay(20, function()"
_t[1140]="            if isSpawnAllowed() then spawnNPC() end"
_t[1141]="        end)"
_t[1142]="    elseif state == \"EndOfDay\" then"
_t[1143]="        -- Clear all active NPCs immediately when the shift ends"
_t[1144]="        local ids = {}"
_t[1145]="        for id in pairs(npcs) do ids[#ids+1] = id end"
_t[1146]="        for _, id in ipairs(ids) do"
_t[1147]="            npcLeave(id, \"end_of_day\")"
_t[1148]="        end"
_t[1149]="    end"
_t[1150]="end)"
_t[1151]=""
_t[1152]="-- ─── CLEANUP ON PLAYER REMOVE ─────────────────────────────────────────────────"
_t[1153]="Players.PlayerRemoving:Connect(function(player)"
_t[1154]="    -- Collect keys first to avoid undefined behavior when mutating during pairs()"
_t[1155]="    local boxesToRemove = {}"
_t[1156]="    for key, pending in pairs(pendingBoxes) do"
_t[1157]="        if pending.carrier == player.Name then"
_t[1158]="            table.insert(boxesToRemove, key)"
_t[1159]="        end"
_t[1160]="    end"
_t[1161]="    for _, key in ipairs(boxesToRemove) do"
_t[1162]="        pendingBoxes[key] = nil"
_t[1163]="    end"
_t[1164]=""
_t[1165]="    -- Auto-confirm any NPC this player triggered that is stuck in cutscene_pending"
_t[1166]="    for npcId, data in pairs(npcs) do"
_t[1167]="        if data.state == \"cutscene_pending\" and data.triggeringPlayer == player then"
_t[1168]="            confirmOrder(player, npcId)"
_t[1169]="        end"
_t[1170]="    end"
_t[1171]="end)"
_t[1172]=""
_t[1173]="-- (duplicate GameState listener removed — first one at line ~887 handles this)"
_t[1174]=""
_t[1175]="-- Wire Rush Hour BindableEvents"
_t[1176]="local ssEvents = game:GetService(\"ServerStorage\"):FindFirstChild(\"Events\")"
_t[1177]="if ssEvents then"
_t[1178]="    local rushStartBE = ssEvents:FindFirstChild(\"RushHourStart\")"
_t[1179]="    local rushEndBE   = ssEvents:FindFirstChild(\"RushHourEnd\")"
_t[1180]="    if rushStartBE then rushStartBE.Event:Connect(function() rushHourActive = true  end) end"
_t[1181]="    if rushEndBE   then rushEndBE.Event:Connect(function()   rushHourActive = false end) end"
_t[1182]="end"
_t[1183]=""
_t[1184]="print(\"[NPCController] Ready\")"