_t[1]="-- NPCController (PersistentNPCSpawner)"
_t[2]="-- Full NPC customer lifecycle:"
_t[3]="--   spawn → walk to queue → wait → player takes order →"
_t[4]="--   walk to seat → wait → box ready → walk to counter →"
_t[5]="--   player delivers → NPC leaves"
_t[6]=""
_t[7]="local Players             = game:GetService(\"Players\")"
_t[8]="local ReplicatedStorage   = game:GetService(\"ReplicatedStorage\")"
_t[9]="local ServerScriptService = game:GetService(\"ServerScriptService\")"
_t[10]="local Workspace           = game:GetService(\"Workspace\")"
_t[11]="local PhysicsService      = game:GetService(\"PhysicsService\")"
_t[12]=""
_t[13]="local NPCSpawner        = require(ReplicatedStorage:WaitForChild(\"Modules\"):WaitForChild(\"NPCSpawner\"))"
_t[14]="local OrderManager      = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"OrderManager\"))"
_t[15]="local CookieData        = require(ReplicatedStorage:WaitForChild(\"Modules\"):WaitForChild(\"CookieData\"))"
_t[16]="local RemoteManager     = require(ReplicatedStorage:WaitForChild(\"Modules\"):WaitForChild(\"RemoteManager\"))"
_t[17]="local EconomyManager    = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"EconomyManager\"))"
_t[18]="local PlayerDataManager = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"PlayerDataManager\"))"
_t[19]="local SessionStats          = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"SessionStats\"))"
_t[20]="local DailyChallengeManager  = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"DailyChallengeManager\"))"
_t[21]="local WeeklyChallengeManager   = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"WeeklyChallengeManager\"))"
_t[22]="local LifetimeChallengeManager = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"LifetimeChallengeManager\"))"
_t[23]="local MenuManager              = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"MenuManager\"))"
_t[24]="local GamepassManager          = require(ServerScriptService:WaitForChild(\"Core\"):WaitForChild(\"GamepassManager\"))"
_t[25]=""
_t[26]="-- ─── CONSTANTS ────────────────────────────────────────────────────────────────"
_t[27]="local MAX_NPCS_IN_SCENE    = 6"
_t[28]="local MAX_QUEUE_SIZE       = 3"
_t[29]="local SPAWN_INTERVAL       = 60   -- seconds between NPC spawn attempts"
_t[30]="local RUSH_SPAWN_INTERVAL  = 20   -- spawn interval during Rush Hour"
_t[31]="local BASE_PATIENCE        = 120     -- seconds at 1 player"
_t[32]="local PATIENCE_PER_PLAYER  = 20      -- extra seconds per additional player"
_t[33]="local VIP_CHANCE           = 0.10"
_t[34]="local PACK_SIZES           = { 1, 4, 6 }"
_t[35]="local VARIETY_PACK_SIZES   = { 4, 6 }"
_t[36]="local VARIETY_CHANCE       = 0.40  -- 40% chance of variety pack when 2+ types in warmer"
_t[37]=""
_t[38]="local SPAWN_STATES = { \"Open\" }  -- NPCs only arrive when the store is open"
_t[39]=""
_t[40]="math.randomseed(tick())  -- Seed RNG so VIP rolls aren't identical each run"
_t[41]=""
_t[42]="local NPC_NAMES = {"
_t[43]="    \"Alex\", \"Sam\", \"Jordan\", \"Riley\", \"Morgan\", \"Casey\", \"Taylor\","
_t[44]="    \"Jamie\", \"Quinn\", \"Drew\", \"Avery\", \"Skylar\", \"Rowan\", \"Blake\","
_t[45]="    \"Reese\", \"Finley\", \"Dakota\", \"Sage\", \"River\", \"Phoenix\","
_t[46]="}"
_t[47]=""
_t[48]="-- ─── STUDIO OBJECTS ───────────────────────────────────────────────────────────"
_t[49]="local QUEUE_FOLDER  = Workspace:WaitForChild(\"NPCQueue\",       10)"
_t[50]="local SPAWN_PART    = Workspace:WaitForChild(\"NPCSpawnPoint\",  10)"
_t[51]="local COUNTER_PART  = Workspace:WaitForChild(\"NPCCounterSpot\", 10)"
_t[52]="local WAITING_AREA  = Workspace:WaitForChild(\"WaitingArea\",    10)"
_t[53]=""
_t[54]="local POS_OBJ       = Workspace:WaitForChild(\"POS\",  10)"
_t[55]="local TABLET_PART   = POS_OBJ    and POS_OBJ:FindFirstChild(\"Tablet\")"
_t[56]="local ORDER_DISPLAY = TABLET_PART and TABLET_PART:FindFirstChild(\"OrderDisplay\")"
_t[57]="local DISPLAY_FRAME = ORDER_DISPLAY and ORDER_DISPLAY:FindFirstChildOfClass(\"Frame\")"
_t[58]=""
_t[59]="-- Remotes"
_t[60]="local boxCarriedRemote         = RemoteManager.Get(\"BoxCarried\")          -- H-8: carry indicator"
_t[61]="local deliveryResult           = RemoteManager.Get(\"DeliveryResult\")"
_t[62]="local hudUpdate                = RemoteManager.Get(\"HUDUpdate\")"
_t[63]="local startOrderCutsceneRemote = RemoteManager.Get(\"StartOrderCutscene\")"
_t[64]="local confirmOrderRemote       = RemoteManager.Get(\"ConfirmNPCOrder\")"
_t[65]="local forceDropBoxRemote       = RemoteManager.Get(\"ForceDropBox\")"
_t[66]="local npcOrderCancelledRemote  = RemoteManager.Get(\"NPCOrderCancelledClient\")"
_t[67]="local comboUpdateRemote        = RemoteManager.Get(\"ComboUpdate\")       -- S-9"
_t[68]="local npcOrderFailedRemote     = RemoteManager.Get(\"NPCOrderFailed\")    -- S-4"
_t[69]="local npcPatienceRemote        = RemoteManager.Get(\"NPCPatienceUpdate\") -- S-6"
_t[70]="local npcOrderReadyRemote      = RemoteManager.Get(\"NPCOrderReady\")"
_t[71]="local deliveryFeedbackRemote   = RemoteManager.Get(\"DeliveryFeedback\")"
_t[72]=""
_t[73]="-- ─── STATE ────────────────────────────────────────────────────────────────────"
_t[74]="local rushHourActive = false  -- set by RushHourStart/End BindableEvents"
_t[75]=""
_t[76]="local npcs        = {}  -- npcId -> npc data"
_t[77]="local npcQueue    = {}  -- ordered list: npcIds currently in the POS queue"
_t[78]="local pendingBoxes = {} -- \"npc_<id>\" -> { boxId, carrier, npcId }"
_t[79]="local nextNpcId   = 1"
_t[80]=""
_t[81]="-- BUG-13: Register \"NPCs\" collision group so NPC HumanoidRootParts do not"
_t[82]="-- collide with each other (prevents ceiling-lift when NPCs converge in doorways)."
_t[83]="do"
_t[84]="    local ok = pcall(function()"
_t[85]="        PhysicsService:RegisterCollisionGroup(\"NPCs\")"
_t[86]="        PhysicsService:CollisionGroupSetCollidable(\"NPCs\", \"NPCs\", false)"
_t[87]="    end)"
_t[88]="    if not ok then"
_t[89]="        -- Group may already exist (server restart); ensure non-collidable"
_t[90]="        pcall(function()"
_t[91]="            PhysicsService:CollisionGroupSetCollidable(\"NPCs\", \"NPCs\", false)"
_t[92]="        end)"
_t[93]="    end"
_t[94]="end"
_t[95]=""
_t[96]="local function pendingKeyForNpc(npcId)"
_t[97]="    return \"npc_\" .. tostring(npcId)"
_t[98]="end"
_t[99]=""
_t[100]="-- ─── HELPERS ──────────────────────────────────────────────────────────────────"
_t[101]=""
_t[102]="-- Build a display label for variety orders: \"C&C x2, Pink Sugar, Snickerdoodle\""
_t[103]="local function buildVarietyLabel(items)"
_t[104]="    if not items or #items == 0 then return \"Mix\" end"
_t[105]="    local counts = {}; local order = {}"
_t[106]="    for _, id in ipairs(items) do"
_t[107]="        if not counts[id] then counts[id] = 0; table.insert(order, id) end"
_t[108]="        counts[id] += 1"
_t[109]="    end"
_t[110]="    local parts = {}"
_t[111]="    for _, id in ipairs(order) do"
_t[112]="        local cookie = CookieData.GetById(id)"
_t[113]="        local name   = cookie and cookie.name or id"
_t[114]="        local cnt    = counts[id]"
_t[115]="        table.insert(parts, cnt > 1 and (name .. \" x\" .. cnt) or name)"
_t[116]="    end"
_t[117]="    return table.concat(parts, \", \")"
_t[118]="end"
_t[119]=""
_t[120]="local function countNPCs()"
_t[121]="    local n = 0"
_t[122]="    for _ in pairs(npcs) do n += 1 end"
_t[123]="    return n"
_t[124]="end"
_t[125]=""
_t[126]="local function getPatienceTime()"
_t[127]="    local pc = math.max(1, #Players:GetPlayers())"
_t[128]="    local base = BASE_PATIENCE + (pc - 1) * PATIENCE_PER_PLAYER"
_t[129]="    -- Apply patience upgrade from any player in server (co-op benefit)"
_t[130]="    local patienceBonus = 0"
_t[131]="    for _, p in ipairs(Players:GetPlayers()) do"
_t[132]="        local stations, _ = PlayerDataManager.GetUnlocks(p)"
_t[133]="        local hasP2, hasP1 = false, false"
_t[134]="        for _, id in ipairs(stations) do"
_t[135]="            if id == \"patience_boost_2\" then hasP2 = true end"
_t[136]="            if id == \"patience_boost_1\" then hasP1 = true end"
_t[137]="        end"
_t[138]="        local bonus = hasP2 and 20 or (hasP1 and 10 or 0)"
_t[139]="        if bonus > patienceBonus then patienceBonus = bonus end"
_t[140]="    end"
_t[141]="    return base + patienceBonus"
_t[142]="end"
_t[143]=""
_t[144]="local function formatTime(secs)"
_t[145]="    local s = math.max(0, math.floor(secs))"
_t[146]="    return string.format(\"%d:%02d\", math.floor(s / 60), s % 60)"
_t[147]="end"
_t[148]=""
_t[149]="local function getQueuePos(slot)"
_t[150]="    if not QUEUE_FOLDER then return nil end"
_t[151]="    local part = QUEUE_FOLDER:FindFirstChild(\"QueueSpot\" .. slot)"
_t[152]="    return part and (part.Position + Vector3.new(0, 2, 0)) or nil"
_t[153]="end"
_t[154]=""
_t[155]="local function getSpawnCFrame()"
_t[156]="    local p = SPAWN_PART and SPAWN_PART.Position or Vector3.new(-5, 2, 30)"
_t[157]="    return CFrame.new(p + Vector3.new(0, 2, 0))"
_t[158]="end"
_t[159]=""
_t[160]="local function getCounterPos()"
_t[161]="    return COUNTER_PART and (COUNTER_PART.Position + Vector3.new(0, 2, 0)) or Vector3.new(20, 2, 20)"
_t[162]="end"
_t[163]=""
_t[164]="local function getFreeWaitSpot()"
_t[165]="    if not WAITING_AREA then return nil end"
_t[166]="    local used = {}"
_t[167]="    for _, data in pairs(npcs) do"
_t[168]="        if data.waitSpot then used[data.waitSpot] = true end"
_t[169]="    end"
_t[170]="    for _, spot in ipairs(WAITING_AREA:GetChildren()) do"
_t[171]="        if spot:IsA(\"Part\") and not used[spot.Name] then return spot end"
_t[172]="    end"
_t[173]="    return nil"
_t[174]="end"
_t[175]=""
_t[176]="local function calcPrice(cookieId, packSize)"
_t[177]="    local cookie = CookieData.GetById(cookieId)"
_t[178]="    return (cookie and cookie.price or 5) * packSize"
_t[179]="end"
_t[180]=""
_t[181]="local function pickRandomName()"
_t[182]="    return NPC_NAMES[math.random(1, #NPC_NAMES)]"
_t[183]="end"
_t[184]=""
_t[185]="-- Returns true if the current game state allows NPC spawning."
_t[186]="local function isSpawnAllowed()"
_t[187]="    local state = Workspace:GetAttribute(\"GameState\") or \"Lobby\""
_t[188]="    for _, s in ipairs(SPAWN_STATES) do"
_t[189]="        if state == s then return true end"
_t[190]="    end"
_t[191]="    return false"
_t[192]="end"
_t[193]=""
_t[194]="-- Rotates the NPC to face the nearest POS station model."
_t[195]="local POS_FOLDER = Workspace:WaitForChild(\"POS\", 10)"
_t[196]=""
_t[197]="-- Face NPC toward a world position (flattened to XZ plane)."
_t[198]="-- H-1 fix: wait 0.2s so Humanoid pathfinding fully settles, then disable"
_t[199]="-- AutoRotate while snapping CFrame so physics can't override it."
_t[200]="local function facePosition(npcModel, targetPos)"
_t[201]="    task.spawn(function()"
_t[202]="        task.wait(0.2)"
_t[203]="        local hrp = npcModel and npcModel:FindFirstChild(\"HumanoidRootPart\")"
_t[204]="        local hum = npcModel and npcModel:FindFirstChildOfClass(\"Humanoid\")"
_t[205]="        if not hrp or not hum then return end"
_t[206]="        local npcPos = hrp.Position"
_t[207]="        local dir = Vector3.new(targetPos.X - npcPos.X, 0, targetPos.Z - npcPos.Z)"
_t[208]="        if dir.Magnitude > 0.1 then"
_t[209]="            hum.AutoRotate = false"
_t[210]="            hrp.CFrame = CFrame.new(npcPos, npcPos + dir)"
_t[211]="            hrp.AssemblyLinearVelocity  = Vector3.zero"
_t[212]="            hrp.AssemblyAngularVelocity = Vector3.zero"
_t[213]="            task.wait(0.1)"
_t[214]="            hum.AutoRotate = true"
_t[215]="        end"
_t[216]="    end)"
_t[217]="end"
_t[218]=""
_t[219]="local function faceClosestPOS(npcModel)"
_t[220]="    if not POS_FOLDER then return end"
_t[221]="    local hrp = npcModel:FindFirstChild(\"HumanoidRootPart\")"
_t[222]="    if not hrp then return end"
_t[223]="    local npcPos     = hrp.Position"
_t[224]="    local bestTarget = nil"
_t[225]="    local bestDist   = math.huge"
_t[226]="    for _, child in ipairs(POS_FOLDER:GetChildren()) do"
_t[227]="        if child:IsA(\"Model\") and child.Name ~= \"DisplayBox\" then"
_t[228]="            local cf, _ = child:GetBoundingBox()"
_t[229]="            local dist  = (cf.Position - npcPos).Magnitude"
_t[230]="            if dist < bestDist then"
_t[231]="                bestDist   = dist"
_t[232]="                bestTarget = cf.Position"
_t[233]="            end"
_t[234]="        end"
_t[235]="    end"
_t[236]="    if bestTarget then"
_t[237]="        local dir = Vector3.new(bestTarget.X - npcPos.X, 0, bestTarget.Z - npcPos.Z)"
_t[238]="        if dir.Magnitude > 0.1 then"
_t[239]="            hrp.CFrame = CFrame.new(npcPos, npcPos + dir)"
_t[240]="        end"
_t[241]="    end"
_t[242]="end"
_t[243]=""
_t[244]="-- ─── TABLET DISPLAY ───────────────────────────────────────────────────────────"
_t[245]="local function updateTabletDisplay(orderData)"
_t[246]="    if not DISPLAY_FRAME then return end"
_t[247]="    local header    = DISPLAY_FRAME:FindFirstChild(\"Header\")"
_t[248]="    local cookLbl   = DISPLAY_FRAME:FindFirstChild(\"CookieLabel\")"
_t[249]="    local priceLbl  = DISPLAY_FRAME:FindFirstChild(\"PriceLabel\")"
_t[250]="    local statusLbl = DISPLAY_FRAME:FindFirstChild(\"StatusLabel\")"
_t[251]=""
_t[252]="    if orderData then"
_t[253]="        local cookie = CookieData.GetById(orderData.cookieId)"
_t[254]="        if header  then header.Text  = orderData.isVIP and \"VIP ORDER\" or \"CURRENT ORDER\" end"
_t[255]="        if cookLbl then"
_t[256]="            cookLbl.Text = orderData.items"
_t[257]="                and (\"Variety Pack  ×\" .. orderData.packSize)"
_t[258]="                or  ((cookie and cookie.name or orderData.cookieId) .. \"  x\" .. orderData.packSize)"
_t[259]="        end"
_t[260]="        if priceLbl  then priceLbl.Text  = orderData.price .. \" coins potential\"            end"
_t[261]="        if statusLbl then statusLbl.Text = orderData.status or \"In kitchen...\"              end"
_t[262]="    else"
_t[263]="        if header    then header.Text    = \"NO ORDERS\"                           end"
_t[264]="        if cookLbl   then cookLbl.Text   = \"\"                                    end"
_t[265]="        if priceLbl  then priceLbl.Text  = \"\"                                    end"
_t[266]="        if statusLbl then statusLbl.Text = \"Press E on customer to take order\"   end"
_t[267]="    end"
_t[268]="end"
_t[269]=""
_t[270]="-- ─── FORWARD DECLARATIONS ─────────────────────────────────────────────────────"
_t[271]="local takeOrder, npcLeave, advanceQueue, addDeliverPrompt"
_t[272]=""
_t[273]="-- ─── TAKE ORDER ───────────────────────────────────────────────────────────────"
_t[274]="takeOrder = function(player, npcId)"
_t[275]="    local data = npcs[npcId]"
_t[276]="    if not data then return end"
_t[277]="    if data.state ~= \"waiting_in_queue\" then return end"
_t[278]="    if data.queueSlot ~= 1 then return end"
_t[279]=""
_t[280]="    -- Force pink_sugar during tutorial"
_t[281]="    local isTutorial = player:GetAttribute(\"InTutorial\")"
_t[282]="    local cookie, packSize, price, varItems"
_t[283]=""
_t[284]="    if isTutorial then"
_t[285]="        cookie   = CookieData.GetById(\"pink_sugar\")"
_t[286]="        packSize = PACK_SIZES[math.random(1, #PACK_SIZES)]"
_t[287]="        price    = calcPrice(cookie.id, packSize)"
_t[288]="    else"
_t[289]="        -- Check warmer stock for variety eligibility"
_t[290]="        local warmerCounts   = OrderManager.GetWarmerCountsByType()"
_t[291]="        local availableTypes = {}"
_t[292]="        for cId, cnt in pairs(warmerCounts) do"
_t[293]="            if cnt > 0 then table.insert(availableTypes, cId) end"
_t[294]="        end"
_t[295]=""
_t[296]="        if #availableTypes >= 2 and math.random() < VARIETY_CHANCE then"
_t[297]="            -- ── Variety pack ──────────────────────────────────────────────────"
_t[298]="            packSize = VARIETY_PACK_SIZES[math.random(1, #VARIETY_PACK_SIZES)]"
_t[299]="            local numTypes = math.random(2, math.min(#availableTypes, packSize))"
_t[300]=""